"""empty message

Revision ID: bba0da36668c
Revises: 70ba48d7eb0b
Create Date: 2023-12-01 18:02:17.753732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba0da36668c'
down_revision = '70ba48d7eb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_teams_name_mlb_id', 'teams', type_='unique')
    op.create_unique_constraint(None, 'teams', ['name'])
    op.create_unique_constraint(None, 'teams', ['mlb_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'teams', type_='unique')
    op.create_unique_constraint('uq_teams_name_mlb_id', 'teams', ['name', 'mlb_id'])
    # ### end Alembic commands ###
